### PR TITLE
build: add --dissable-doc

### PR DESCRIPTION
**Pull request by alonbl**
useful to reduce image size on selected distributions.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

### CODE REVIEW

**Comment by philwhineray** [comment]
Seems fine so I will merge.

Note that manual pages are still installed, it is just the HTML and PDF manuals which are stopped, which I presume is intentional.

**Comment by alonbl** [comment]
thanks!

yes, man pages are installed, I can add --disable-man as well.

**Comment by philwhineray** [comment]
I would expect there is no need at present unless you have a particularly small system.

**Comment by philwhineray** [comment]
Oh - and I should say thanks for submitting some code, too!

**Comment by alonbl** [comment]
thank you!

I am using this since ~2006, and I was very happy to see this release!

It is exactly what I require and expect to have.

**Pull request merged**
